// Customer types
export const CUSTOMER_REGISTER_ERRORS = "CUSTOMER_REGISTER_ERRORS";
export const CUSTOMER_LOGIN_ERRORS = "CUSTOMER_LOGIN_ERRORS";
export const CUSTOMER_REGISTER_SUCCESS = "CUSTOMER_REGISTER_SUCCESS";
export const CUSTOMER_LOGIN_SUCCESS = "CUSTOMER_LOGIN_SUCCESS";
export const RESTAURANT_SELECTED = "RESTAURANT_SELECTED";

// Driver types
export const DRIVER_REGISTER_ERRORS = "DRIVER_REGISTER_ERRORS";
export const DRIVER_LOGIN_ERRORS = "DRIVER_LOGIN_ERRORS";
export const DRIVER_REGISTER_SUCCESS = "DRIVER_REGISTER_SUCCESS";
export const DRIVER_LOGIN_SUCCESS = "DRIVER_LOGIN_SUCCESS";

// Admin types
export const ADMIN_LOGIN_ERRORS = "ADMIN_LOGIN_ERRORS";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADD_RESTAURANT_ERRORS = "ADD_RESTAURANT_ERRORS";
export const ADD_RESTAURANT_SUCCESS = "ADD_RESTAURANT_SUCCESS";
